# Generated by Django 3.2.5 on 2021-08-03 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_check',
            name='s_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student_check'),
        ),
    ]
