# Generated by Django 3.2.5 on 2021-08-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_check_s_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_check',
            name='s_check',
        ),
    ]
